### ISSUE TITLE
change /alert to not be boss bar but to be a /title

### ISSUE THREAD

**Issue by MODKILLER1001** [Warvale/Issues#5]
can it be a /title to  see it easier

**Comment by Pixelific** [comment]
Currently it's in the boss bar and it's a little bugged (as it stays there, does not go away, and gives a NullPointerException in chat). I think it would be best to change it from being on bossbar to just showing in chat instead.

**Comment by MODKILLER1001** [comment]
what about a /title

**Comment by RONTheCookie** [comment]
Gonna do when I get home, issue is here [AlertCommand.java](https://github.com/Warvale/StaffCore/blob/18051956f397a634409c73067b1d270fda9fca8d/src/main/java/net/warvale/staffcore/commands/basic/AlertCommand.java)
