### ISSUE TITLE
colored names

### ISSUE THREAD

**Issue by MODKILLER1001** [Warvale/Issues#9]
colored names are not showing in /sc and can the /color command be /namecolor with a GU I

**Comment by RONTheCookie** [comment]
I dont understand the problem 🍭

**Comment by RONTheCookie** [comment]
Will fix when I get home, issue is here: [StaffChatCommand.java(https://github.com/Warvale/StaffCore/blob/a659737f11359263dc1b5f12fb44e3750861bcde/src/main/java/net/warvale/staffcore/commands/staff/StaffChatCommand.java)

**Comment by RONTheCookie** [comment]
Fixed.
